image: node:latest

stages:
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - cd todolist
    - npm install
    - npm run build
  artifacts:
    paths:
      - node_modules/