# Generated by Django 2.1.3 on 2018-11-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyapi', '0002_auto_20181125_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetable',
            name='image_alt_text',
            field=models.TextField(default='sadffassdf'),
            preserve_default=False,
        ),
    ]
